import React from "react";
export const destinations = [
    {
        id: "1",
        title: "Bali Paradise Retreat",
        location: "Bali, Indonesia",
        description:
            "Experience the magic of Bali with its lush landscapes, pristine beaches, and vibrant culture. Our exclusive retreat offers a perfect blend of relaxation and adventure in the Island of Gods.",
        image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1374&q=80",
        price: 1299,
        rating: 4.8,
        duration: "7 days",
        featured: true,
        activities: [
            "Temple Visits",
            "Surfing Lessons",
            "Rice Terrace Trekking",
            "Spa Treatments",
            "Cooking Classes",
        ],
        inclusions: [
            "Accommodation",
            "Breakfast",
            "Airport Transfer",
            "Welcome Dinner",
        ],
    },
    {
        id: "2",
        title: "Paris City of Lights Tour",
        location: "Paris, France",
        description:
            "Discover the romance and charm of Paris, the City of Lights. Explore iconic landmarks, savor exquisite cuisine, and immerse yourself in the rich cultural heritage of this timeless European capital.",
        image: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1473&q=80",
        price: 1599,
        rating: 4.7,
        duration: "5 days",
        featured: true,
        activities: [
            "Eiffel Tower Visit",
            "Louvre Museum Tour",
            "Seine River Cruise",
            "Montmartre Walking Tour",
            "Wine Tasting",
        ],
        inclusions: [
            "Accommodation",
            "Breakfast",
            "Museum Passes",
            "Seine Dinner Cruise",
        ],
    },
    {
        id: "3",
        title: "Santorini Island Escape",
        location: "Santorini, Greece",
        description:
            "Indulge in the breathtaking beauty of Santorini, with its iconic white-washed buildings and stunning sunsets over the Aegean Sea. Experience Greek hospitality at its finest on this idyllic island getaway.",
        image: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1374&q=80",
        price: 1899,
        rating: 4.9,
        duration: "6 days",
        featured: false,
        activities: [
            "Caldera Sunset Viewing",
            "Winery Tours",
            "Boat Trip to Volcano",
            "Red Beach Visit",
            "Greek Cooking Class",
        ],
        inclusions: [
            "Accommodation",
            "Breakfast",
            "Airport Transfer",
            "Sunset Dinner",
        ],
    },
    {
        id: "4",
        title: "Tokyo Cultural Immersion",
        location: "Tokyo, Japan",
        description:
            "Dive into the fascinating blend of ancient traditions and cutting-edge technology in Tokyo. From historic temples to futuristic skyscrapers, experience the unique culture and cuisine of Japan's capital.",
        image: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1371&q=80",
        price: 2199,
        rating: 4.6,
        duration: "8 days",
        featured: false,
        activities: [
            "Meiji Shrine Visit",
            "Tsukiji Fish Market Tour",
            "Akihabara Electronics District",
            "Sumo Wrestling Experience",
            "Mt. Fuji Day Trip",
        ],
        inclusions: [
            "Accommodation",
            "Breakfast",
            "Tokyo Metro Pass",
            "Tea Ceremony",
        ],
    },
    {
        id: "5",
        title: "New York City Explorer",
        location: "New York, USA",
        description:
            "Experience the energy and diversity of the Big Apple. From iconic landmarks to world-class museums, Broadway shows to diverse neighborhoods, discover why New York is one of the world's most exciting cities.",
        image: "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80",
        price: 1799,
        rating: 4.5,
        duration: "5 days",
        featured: false,
        activities: [
            "Statue of Liberty Visit",
            "Central Park Tour",
            "Broadway Show",
            "MoMA & Met Museum",
            "Brooklyn Bridge Walk",
        ],
        inclusions: [
            "Accommodation",
            "City Pass",
            "Airport Transfer",
            "Broadway Tickets",
        ],
    },
    {
        id: "6",
        title: "Machu Picchu Adventure",
        location: "Cusco, Peru",
        description:
            "Embark on an unforgettable journey to the ancient Incan citadel of Machu Picchu. Trek through stunning Andean landscapes and explore the rich cultural heritage of Peru on this once-in-a-lifetime adventure.",
        image: "https://images.unsplash.com/photo-1526392060635-9d6019884377?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80",
        price: 2399,
        rating: 4.9,
        duration: "9 days",
        featured: true,
        activities: [
            "Machu Picchu Guided Tour",
            "Sacred Valley Exploration",
            "Cusco City Tour",
            "Traditional Weaving Workshop",
            "Inca Trail Hiking",
        ],
        inclusions: [
            "Accommodation",
            "Breakfast & Dinner",
            "Train Tickets",
            "Entrance Fees",
        ],
    },
];
export const bookings = [
    {
        id: "1",
        userId: "2",
        destinationId: "1",
        startDate: "2023-06-15",
        endDate: "2023-06-22",
        travelers: 2,
        totalPrice: 2598,
        status: "confirmed",
        createdAt: "2023-05-01T10:30:00Z",
    },
    {
        id: "2",
        userId: "2",
        destinationId: "3",
        startDate: "2023-07-10",
        endDate: "2023-07-16",
        travelers: 1,
        totalPrice: 1899,
        status: "pending",
        createdAt: "2023-05-05T14:20:00Z",
    },
    {
        id: "3",
        userId: "2",
        destinationId: "2",
        startDate: "2023-08-05",
        endDate: "2023-08-10",
        travelers: 3,
        totalPrice: 4797,
        status: "confirmed",
        createdAt: "2023-05-10T09:15:00Z",
    },
];
export const reviews = [
    {
        id: "1",
        userId: "2",
        destinationId: "1",
        rating: 5,
        comment:
            "Absolutely stunning experience! The retreat was everything we hoped for and more. The staff was incredibly attentive, and the activities were perfectly balanced between relaxation and adventure.",
        createdAt: "2023-04-15T16:30:00Z",
        userName: "Regular User",
    },
    {
        id: "2",
        userId: "2",
        destinationId: "2",
        rating: 4,
        comment:
            "Beautiful city with so much to see! The tour was well organized, though a bit rushed at times. Would recommend adding an extra day to fully appreciate all the sights.",
        createdAt: "2023-03-22T11:45:00Z",
        userName: "Regular User",
    },
    {
        id: "3",
        userId: "2",
        destinationId: "6",
        rating: 5,
        comment:
            "A life-changing journey! Machu Picchu exceeded all expectations. Our guide was knowledgeable and passionate, making the history come alive. The trek was challenging but absolutely worth it!",
        createdAt: "2023-02-18T14:10:00Z",
        userName: "Regular User",
    },
];
export const users = [
    {
        id: "1",
        name: "Admin User",
        email: "admin@travelease.com",
        isAdmin: true,
        createdAt: "2023-01-01T00:00:00Z",
    },
    {
        id: "2",
        name: "Regular User",
        email: "user@travelease.com",
        isAdmin: false,
        createdAt: "2023-01-15T00:00:00Z",
    },
    {
        id: "3",
        name: "Jane Smith",
        email: "jane@example.com",
        isAdmin: false,
        createdAt: "2023-02-10T00:00:00Z",
    },
    {
        id: "4",
        name: "John Doe",
        email: "john@example.com",
        isAdmin: false,
        createdAt: "2023-03-05T00:00:00Z",
    },
];
